version: '3.4'
services:
  srebot:
    image: "ashleypoole/srebotweb:latest"
    ports:
      - "8000:80"
    environment:
     - "Bot:SlackApiKey=${SLACK_API_KEY}"
     - "IncidentManagement:IncidentNotificationChannel=${INCIDENT_CHANNEL_NAME}"
     - "IncidentManagement:warrooms=${INCIDENT_WARROOM_NAMES}"
     - "IncidentManagement:AzureConnectionString=${INCIDENT_AZURE_CONNECTION_STRING}"
     - "IncidentManagement:PostmortemTemplateLink=${INCIDENT_POSTMORTEM_LINK}"
     - "IncidentManagement.Web:ChannelBaseUrl=${SLACK_CHANNEL_BASE_URL}"
     - "Cloudflare:AuthEmail=${CLOUDFLARE_AUTH_EMAIL}"
     - "Cloudflare:AuthKey=${CLOUDFLARE_AUTH_KEY}"
     - "Cloudflare:ApiUrl=https://api.cloudflare.com/client/v4"
    deploy:
      restart_policy:
        condition: any
        delay: 20s
        max_attempts: 10
        window: 360s